# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyj6vIMY_U0H69o9eYUhJnsyJ4A5el6e
"""

from data_module import PrivacyPreservingData
from ml_module import WebAnalyzerML
from visualization import visualize_confusion_matrix
from simulation import real_time_simulation

def main():
    # Step 1: Load and preprocess
    data_module = PrivacyPreservingData()
    df = data_module.load_dataset()
    X, y, vectorizer = data_module.preprocess()
    print("=== Sample Dataset with Hashed URLs ===")
    print(df.head(), "\n")

    # Step 2: Train Model
    ml_module = WebAnalyzerML(vectorizer)
    accuracy, cm, report = ml_module.train(X, y)
    print("=== Model Performance ===")
    print("Accuracy:", round(accuracy*100, 2), "%")
    print("Classification Report:\n", report)
    visualize_confusion_matrix(cm)
    ml_module.visualize_tree()

    # Step 3: Real-Time Simulation
    real_time_simulation(ml_module, data_module)

if __name__ == "__main__":
    main()