# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyj6vIMY_U0H69o9eYUhJnsyJ4A5el6e
"""

import matplotlib.pyplot as plt
import seaborn as sns

def visualize_confusion_matrix(cm):
    """Plot confusion matrix heatmap"""
    plt.figure(figsize=(6,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=["Safe", "Suspicious"],
                yticklabels=["Safe", "Suspicious"])
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()